name: textbook

channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
dependencies:
  - python=3.6
  - tensorflow
  - bqplot
  - datascience
  - numpy < 2
  - scipy
  - datascience
  - jupyter-book
  - matplotlib==3.2
  - pandas
  - ipywidgets==7.0.0
