#!/bin/bash
pip install -r requirements.txt 
python -m pip install -U matplotlib==3.2 datascience numpy scipy bqplot jupyter-book
jupyter nbextension enable --py --sys-prefix widgetsnbextension
jupyter nbextension enable --py --sys-prefix bqplot